- src/Notifier/CliBasedNotifier.php
> Fixed typo

- tests/NotifierFactoryTest.php
- tests/Util/OsHelperTest.php
- tests/Util/PharExtractorTest.php
> Fixed typo in tribute of @xavierlacot

- README.md
- doc/01-basic-usage.md
- example/index.php
- src/NotifierFactory.php
This PR will be merged before #9 so it will probably be tagged as 1.0.2
> Add precision about factory returning null

- CHANGELOG.md
- composer.json
> Allow symfony 3

- src/NotifierFactory.php
> Refactoring in NotifierFactory

- src/Notifier/AppleScriptNotifier.php
https://github.com/jolicode/JoliNotif/issues/24
> fix problem with Monolog integration

- README.md
I don't know if you'll agree with this. My reasoning:
* If you are a newcomer and copy+paste the code ... it won't work. That's a bad impression for the project.
* If you are an experienced user, you know what to do with this line, maintaining or removing it according to where you paste the code.
> Improved the sample script to include the class autoloader

- src/Notifier/CliBasedNotifier.php
> Fixed support of symfony/process 3.3

- README.md
- doc/01-basic-usage.md
- doc/02-notification.md
- src/Notification.php
- src/Notifier/AppleScriptNotifier.php
- tests/Notifier/AppleScriptNotifierTest.php
- tests/Notifier/CliBasedNotifierTestTrait.php
- tests/Notifier/GrowlNotifyNotifierTest.php
- tests/Notifier/NotifuNotifierTest.php
- tests/Notifier/NotifySendNotifierTest.php
- tests/Notifier/TerminalNotifierNotifierTest.php
- tests/Notifier/ToasterNotifierTest.php
With AppleScriptNotifier, we can provide an amazing sound and subtitle in the notification.
> Add sound notification and subtitle for macOS

- CHANGELOG.md
- doc/01-basic-usage.md
- doc/02-notification.md
- src/Notifier/TerminalNotifierNotifier.php
- tests/Notifier/AppleScriptNotifierTest.php
- tests/Notifier/CliBasedNotifierTestTrait.php
- tests/Notifier/TerminalNotifierNotifierTest.php
> Add support for url in terminal-notifier

- CHANGELOG.md
- src/Notification.php
- src/Notifier/ToasterNotifier.php
- src/NotifierFactory.php
- src/Util/OsHelper.php
- tests/Notifier/BinaryProviderTestTrait.php
- tests/Util/OsHelperTest.php
> Add support for Windows Subsystem for Linux

- composer.json
This pull request adds support to symfony 5
> feat: adds support to symfony 5

- .travis.yml
This pull request addresses the test suite adding tests against the near version of symfony components.
> chore: tests against symfony 5

- README.md
- doc/04-advanced-usage.md
- doc/04-cron-usage.md
Fix #71
Inspired by https://askubuntu.com/a/1098206
> Alternate CRON configuration

- README.md
- doc/01-basic-usage.md
- doc/02-notification.md
- doc/04-cron-usage.md
- doc/05-cli-usage.md
Tweaked the rendering of "notes" in the documentation
> Tweak the documentation for better github rendering

- .github/workflows/ci.yml
- Update GitHub Action actions/checkout from v2 to v3
- Update GitHub Action actions/cache from v2 to v3
> Update some GitHub Actions

- src/NotifierFactory.php
- tests/NotifierFactoryTest.php
Fix https://github.com/jolicode/JoliNotif/pull/101#issuecomment-2077065542
> Move WSL notifier to Windows notifier list

- composer.json
> allow lower psr log versions

- composer.json
see https://packagist.org/packages/jolicode/php-os-helper#v0.2.0
> Allow jolicode/php-os-helper ^0.2

- CHANGELOG.md
- composer.json
After https://github.com/jolicode/JoliNotif/pull/123#discussion_r2253611512
> Fix Symfony constraint in `composer.json`
